# ワークフロー名
name: test-bot
# scheduleはデフォルトブランチ以外では動作しない
on:
  workflow_dispatch:

jobs:
  build:
    env:
      CURRENT_DATETIME: null
      CURRENT_HOUR: null
      CURRENT_MINUTE: null
    # ITチームの実行環境(AWS)での実行
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Checkout chemistry-bot repo
        uses: actions/checkout@v3
        # 読み込むリポジトリを指定
        with:
          repository: yy8-kyoto/mypj
          path: mypj
          token: ${{ secrets.TEST_GITHUB_TOKEN_REPO }} 
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd mypj/cbt
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install -r requirements.txt
      - name: Setup timezone
        run: |
          export TZ="Asia/Tokyo"
          # envに現在日時、時刻を設定
          echo "CURRENT_DATETIME=$(date +'%Y/%m/%d/%H')" >> $GITHUB_ENV
          echo "CURRENT_HOUR=$(date +'%H')" >> $GITHUB_ENV
          echo "CURRENT_MINUTE=$(date +'%M')" >> $GITHUB_ENV
      - name: test
        run: |
          echo "test"
          python -m python_test.__main__